#To use:
#    $ conda install -n base -c conda-forge mamba
#    $ conda env create -n mbo-caiman --file /path/to/repo/environment.yml
#    $ conda activate mbo-caiman
name: mbo-caiman
channels:
- defaults
- conda-forge
dependencies:
- pip
- python
- ipython
- sphinx>=6.0
- sphinxcontrib-video
- numpydoc
- sphinx-book-theme
- pip:
  - sphinxcontrib-matlabdomain
  - sphinxcontrib-images
  - myst-nb
  - sphinx-copybutton
  - sphinx-togglebutton
