#To use:
#    $ conda install -n base -c conda-forge mamba
#    $ mamba create -n mbo-caiman -c conda-forge caiman  # match package name
#    $ conda activate mbo-caiman
#    $ conda install -f /path/to/repo/environment.yml
#
name: mbo-caiman  # changing this will mean changing `conda activate <my-package-name>
channels:
- conda-forge
- defaults
dependencies:
- pip
- python <=3.9
- bokeh >=3.1.1
- cython
- holoviews >=1.16.2
- ipykernel
- ipython
- ipyparallel
- jupyter
- jupyter_bokeh
- matplotlib
- moviepy
- nose
- numpy <2.0.0
- scikit-image >=0.19.0
- scikit-learn >=1.2
- scipy >= 1.10.1
- opencv
- panel >=1.0.2
- peakutils
- pims
- psutil
- pynwb
- pyqtgraph
- tk
- tqdm
- yapf
- tifffile
- zarr
- h5py
- pip:
  - -e git+https://github.com/ru-rbo/scanreader.git#egg=argh
  - scanreader
  - sphinxcontrib-matlabdomain
  - sphinxcontrib-images
  - sphinxcontrib-video
  - numpydoc
  - pydata-sphinx-theme
