classdef ResScanPage < scanimage.guis.configuration.ConfigurationPage
    
    properties
        scannerName;
        pxiNum;
        numChans;
        
        hBeamText;
        hBeamPopUp;
        hShutterTable;
        hFlexRIODeviceIDText;
        hFlexRIODeviceIDPopUp;
        hDigitalIODeviceText;
        hDigitalIODevicePopUp;
        hNominalFrequencyText;
        hNominalFrequencyEdit;
        hChannelTable;
        hUseExternalSampleClockCheckBox;
        hExternalSampleClockRateText;
        hExternalSampleClockRateEdit;
        hResonantMirrorPanel;
        hResMaxAngularRangeText;
        hResMaxAngularRangeEdit;
        hResZoomDeviceText;
        hResZoomDevicePopUp;
        hResZoomChannelIDText;
        hResZoomChannelIDPopUp;
        hResMaxVoltageCmdText;
        hResMaxVoltageCmdEdit;
        hResSettlingTimeText;
        hResSettlingTimeEdit;
        hGalvoPanel;
        hGalvoDeviceText;
        hGalvoDevicePopUp;
        hGalvoXGalvoPanel;
        hXGalvoAnalogOutputChannelIDText;
        hXGalvoAnalogOutputChannelIDPopUp;
        hXGalvoMaxAngularRangeText;
        hXGalvoMaxAngularRangeEdit;
        hXGalvoOpticalConversionFactorText;
        hXGalvoOpticalConversionFactorEdit;
        hXGalvoParkAngleText;
        hXGalvoParkAngleEdit;
        hGalvoYGalvoPanel;
        hYGalvoAnalogOutputChannelIDText;
        hYGalvoAnalogOutputChannelIDPopUp;
        hYGalvoMaxAngularRangeText;
        hYGalvoMaxAngularRangeEdit;
        hYGalvoOpticalConversionFactorText;
        hYGalvoOpticalConversionFactorEdit;
        hYGalvoParkAngleText;
        hYGalvoParkAngleEdit;
        
        tfMap = containers.Map({true false}, {'on' 'off'});
        ADAPTER_MODULE_CHANNEL_COUNT = containers.Map({'','NI5732','NI5733','NI5734','NI5751','NI517x'},{2,2,2,4,4,4});
    end
    
    properties (SetObservable)
        acqDev = '';
        digIoDev = '';
        useExtClk = false;
        exprtClk = false;
        zoomCtlDaq = '';
        galvoDaq = '';
        xGalvoChanSel = 1;
        
        galvoFeedbackDaq = '';
    end
    
    properties (Constant)
        defaultPagePath = '+scanimage\+components\+scan2d\private\ResScan_model.m';
    end
    
    methods
        function obj = ResScanPage(hConfigEditor, scannerName, create)
            if nargin < 3 || isempty(create)
                create = false;
            end
            obj = obj@scanimage.guis.configuration.ConfigurationPage(hConfigEditor,create,false,sprintf('ResScan (%s)',scannerName));
            
            ph = 967;
            obj.minimumWidth = 836;
            obj.hPanel = uipanel('parent',[],'BorderType','none','units','pixels', 'position', [0 0 obj.minimumWidth ph]);
        
            % FlexRIODeviceIDText
            obj.hFlexRIODeviceIDText = uicontrol(...
                'parent', obj.hPanel, ...
                'Tag', 'FlexRIODeviceIDText', ...
                'Style', 'text', ...
                'String', 'Signal Acquisition DAQ', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [46 ph-42 200 14]);
        
            % FlexRIODeviceIDPopUp
            obj.hFlexRIODeviceIDPopUp = most.gui.popupMenuEdit(...
                'parent', obj.hPanel, ...
                'Position', [280 ph-46 150 22],...
                'validationFunc',@obj.validateRioChoice,...
                'Bindings',{{obj 'acqDev' 'string'} {obj.hConfigEditor 'rioChoices' 'choices'}});
        
            % DigitalIODeviceText
            obj.hDigitalIODeviceText = uicontrol(...
                'parent', obj.hPanel, ...
                'Tag', 'DigitalIODeviceText', ...
                'Style', 'text', ...
                'String', 'Auxiliary Digital I/O DAQ', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', 'Enter the Device name of the DAQ board that is used for digital inputs/outputs (triggers/clocks etc). It must be installed in the same PXI chassis as the FlexRIO Digitizer.', ...
                'Units', 'pixels', ...
                'Position', [46 ph-89 150 14]);
        
            % DigitalIODevicePopUp
            obj.hDigitalIODevicePopUp = most.gui.popupMenuEdit(...
                'parent', obj.hPanel, ...
                'Position', [280 ph-89 150 22],...
                'validationFunc',@obj.validateDaqChoice,...
                'TooltipString', 'Enter the Device name of the DAQ board that is used for digital inputs/outputs (triggers/clocks etc). It must be installed in the same PXI chassis as the FlexRIO Digitizer.', ...
                'Bindings',{obj 'digIoDev' 'string'});
            
            % BeamText
            obj.hBeamText = uicontrol(...
                'parent', obj.hPanel, ...
                'Tag', 'BeamText', ...
                'Style', 'text', ...
                'String', 'Beam DAQ', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [46 ph-136 100 14]);
        
            % BeamPopUp 
            obj.hBeamPopUp = uicontrol(...
                'parent', obj.hPanel, ...
                'Tag', 'BeamPopUp', ...
                'Style', 'popupmenu', ...
                'String', ' ', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [280 ph-138 150 20]);
        
            % NominalFrequencyText
            obj.hNominalFrequencyText = uicontrol(...
                'parent', obj.hPanel, ...
                'Tag', 'NominalFrequencyText', ...
                'Style', 'text', ...
                'String', 'Nominal Resonant Scanner Frequency (Hz)', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [46 ph-180 250 14]);
        
            % NominalFrequencyEdit 
            obj.hNominalFrequencyEdit = uicontrol(...
                'parent', obj.hPanel, ...
                'Tag', 'NominalFrequencyEdit', ...
                'Style', 'edit', ...
                'String', '7910', ...
                'HorizontalAlignment', 'center', ...
                'Units', 'pixels', ...
                'Position', [280 ph-185 50 22]);
        
            % UseExternalSampleClockCheckBox
            obj.hUseExternalSampleClockCheckBox = most.gui.uicontrol(...
                'parent', obj.hPanel, ...
                'Tag', 'UseExternalSampleClockCheckBox', ...
                'Style', 'checkbox', ...
                'String', 'Use External Sample Clock', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', 'Check if you want to use the external sample clock connected to the CLK IN terminal of the FlexRIO digitizer module.', ...
                'Units', 'pixels', ...
                'Bindings', {obj 'useExtClk' 'value'},...
                'Position', [46 ph-225 160 23]);
        
            % ExternalSampleClockRateText
            obj.hExternalSampleClockRateText = uicontrol(...
                'parent', obj.hPanel, ...
                'Tag', 'ExternalSampleClockRateText', ...
                'Style', 'text', ...
                'String', 'External Sample Clock Rate (Hz)', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', 'Enter the nominal frequency of the external sample clock connected  to the CLK IN terminal (e.g. 80e6). The actual rate is measured on FPGA.', ...
                'Units', 'pixels', ...
                'Position', [46 ph-251 200 14]);
        
            % ExternalSampleClockRateEdit 
            obj.hExternalSampleClockRateEdit = uicontrol(...
                'parent', obj.hPanel, ...
                'Tag', 'ExternalSampleClockRateEdit', ...
                'Style', 'edit', ...
                'String', '', ...
                'HorizontalAlignment', 'center', ...
                'TooltipString', 'Enter the nominal frequency of the external sample clock connected  to the CLK IN terminal (e.g. 80e6). The actual rate is measured on FPGA.', ...
                'Units', 'pixels', ...
                'Position', [280 ph-253 50 22]);
            
            most.gui.uicontrol(...
                'parent', obj.hPanel, ...
                'Style', 'checkbox', ...
                'String', 'Export 10MHz Reference Clock', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', 'Check if you want to export a 10MHz reference clock on PFI14 of the aux digital IO DAQ.', ...
                'Units', 'pixels', ...
                'Bindings', {obj 'exprtClk' 'value'},...
                'Position', [46 ph-298 260 23]);
            
            
            
            uicontrol(...
                'parent', obj.hPanel, ...
                'Style', 'text', ...
                'String', 'Select shutters that must be open when using this scanner.', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [518 ph-37 300 14]);
        
            % ShutterTable
            shutterColumnNames      = {'Select', 'Shutter Device'};
            shutterColumnFormats    = {'logical', 'char'};
            shutterColumnEditable   = [true, false];
            shutterColumnWidths     = {50, 210};
            shutterBlankRow         = {false '';};
            
            obj.hShutterTable = uitable( ... 
                'parent', obj.hPanel, ...
                'Tag', 'ShutterTable', ...
                'Data', shutterBlankRow, ...
                'ColumnName', shutterColumnNames, ...
                'ColumnFormat', shutterColumnFormats, ...
                'ColumnEditable', shutterColumnEditable, ...
                'ColumnWidth', shutterColumnWidths, ...
                'RowName', [], ...
                'RowStriping', 'Off', ...
                'Units', 'pixels', ...
                'Position', [518 ph-142 284 100]);
            
            uicontrol(...
                'parent', obj.hPanel, ...
                'Style', 'text', ...
                'String', 'Indicate channels that have an inverted PMT signal.', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [518 ph-180 300 14]);
            
            % channel table
            obj.hChannelTable = uitable( ... 
                'parent', obj.hPanel, ...
                'ColumnName', {'Digitizer Channel', 'Invert'}, ...
                'ColumnFormat', {'char', 'logical'}, ...
                'ColumnEditable', [false, true], ...
                'ColumnWidth', {110 50}, ...
                'RowName', {}, ...
                'Data', {}, ...
                'RowStriping', 'Off', ...
                'Units', 'pixels', ...
                'Position', [518 ph-284 284 100]);
        
            % ResonantMirrorPanel 
            rph = 275;
            obj.hResonantMirrorPanel = uipanel( ...
                'parent', obj.hPanel, ...
                'Tag', 'ResonantMirrorPanel', ...
                'Title', 'Resonant Mirror', ...    
                'Units', 'pixels', ...
                'Position', [46 ph-589 450 rph]);
        
            % ResZoomDeviceText
            obj.hResZoomDeviceText = uicontrol(...
                'parent', obj.hResonantMirrorPanel, ...
                'Tag', 'ResZoomDeviceText', ...
                'Style', 'text', ...
                'String', 'Zoom Control DAQ', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', 'NI-DAQ board to host the resonant zoom analog output.', ...
                'Units', 'pixels', ...
                'Position', [46 rph-60 150 14]);
        
            % ResZoomDevicePopUp 
            obj.hResZoomDevicePopUp = most.gui.popupMenuEdit(...
                'parent', obj.hResonantMirrorPanel, ...
                'Position', [246 rph-58 150 22],...
                'validationFunc',@obj.validateZoomDaqChoice,...
                'TooltipString', 'NI-DAQ board to host the resonant zoom analog output.', ...
                'Bindings',{obj 'zoomCtlDaq' 'string'});
        
            % ResZoomChannelIDText
            obj.hResZoomChannelIDText = uicontrol(...
                'parent', obj.hResonantMirrorPanel, ...
                'Tag', 'ResZoomChannelIDText', ...
                'Style', 'text', ...
                'String', 'Zoom Control Channel ID', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', 'Analog Output channel ID to be used to control the Resonant Scanner Zoom level.', ...
                'Units', 'pixels', ...
                'Position', [46 rph-104 150 14]);
        
            % ResZoomChannelIDPopUp 
            obj.hResZoomChannelIDPopUp = uicontrol(...
                'parent', obj.hResonantMirrorPanel, ...
                'Tag', 'ResZoomChannelIDPopUp', ...
                'Style', 'popupmenu', ...
                'String', ' ', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', 'Analog Output channel ID to be used to control the Resonant Scanner Zoom level.', ...
                'Units', 'pixels', ...
                'Position', [246 rph-104 50 20]);
        
            % ResOpticalConversionFactorText
            obj.hResMaxVoltageCmdText = uicontrol(...
                'parent', obj.hResonantMirrorPanel, ...
                'Style', 'text', ...
                'String', 'Zoom Control Max Command (V)', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', 'Voltage command that sets the resonant scanner to the maximum angular range. 5V for most resonant scanners.', ...
                'Units', 'pixels', ...
                'Position', [46 rph-150 220 14]);
        
            % ResOpticalConversionFactorEdit 
            obj.hResMaxVoltageCmdEdit = uicontrol(...
                'parent', obj.hResonantMirrorPanel, ...
                'Style', 'edit', ...
                'String', '5', ...
                'HorizontalAlignment', 'center', ...
                'TooltipString', 'Voltage command that sets the resonant scanner to the maximum angular range. 5V for most resonant scanners.', ...
                'Units', 'pixels', ...
                'Position', [246 rph-153 51 22]);
        
            % ResMaxAngularRangeText
            obj.hResMaxAngularRangeText = uicontrol(...
                'parent', obj.hResonantMirrorPanel, ...
                'Tag', 'ResMaxAngularRangeText', ...
                'Style', 'text', ...
                'String', 'Max Angular Range (optical deg pk-pk)', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [46 rph-199 189 14]);
        
            % ResMaxAngularRangeEdit 
            obj.hResMaxAngularRangeEdit = uicontrol(...
                'parent', obj.hResonantMirrorPanel, ...
                'Tag', 'ResMaxAngularRangeEdit', ...
                'Style', 'edit', ...
                'String', '15', ...
                'HorizontalAlignment', 'center', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [246 rph-202 51 22]);
        
            % ResSettlingTimeText
            obj.hResSettlingTimeText = uicontrol(...
                'parent', obj.hResonantMirrorPanel, ...
                'Tag', 'ResSettlingTimeText', ...
                'Style', 'text', ...
                'String', 'Zoom Amplitude Settling Time (sec)', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', 'Time to wait for the resonant scanner to reach desired amplitude after an update.', ...
                'Units', 'pixels', ...
                'Position', [46 rph-242 190 14]);
        
            % ResSettlingTimeEdit 
            obj.hResSettlingTimeEdit = uicontrol(...
                'parent', obj.hResonantMirrorPanel, ...
                'Tag', 'ResSettlingTimeEdit', ...
                'Style', 'edit', ...
                'String', '.5', ...
                'HorizontalAlignment', 'center', ...
                'TooltipString', 'Time to wait for the resonant scanner to reach its desired frequency after an update of the zoom Factor', ...
                'Units', 'pixels', ...
                'Position', [246 rph-245 51 22]);
        
            % GalvoPanel
            gph = 317;
            obj.hGalvoPanel = uipanel( ...
                'parent', obj.hPanel, ...
                'Tag', 'GalvoPanel', ...
                'Title', 'Galvo Settings', ...    
                'Units', 'pixels', ...
                'Position', [46 ph-941 810 gph]);
        
            % GalvoDeviceText
            obj.hGalvoDeviceText = uicontrol(...
                'parent', obj.hGalvoPanel, ...
                'Tag', 'GalvoDeviceText', ...
                'Style', 'text', ...
                'String', 'Galvo Position Control DAQ', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [46 gph-50 190 14]);
        
            % GalvoDevicePopUp
            obj.hGalvoDevicePopUp = most.gui.popupMenuEdit(...
                'parent', obj.hGalvoPanel, ...
                'Position', [246 gph-51 150 22],...
                'validationFunc',@obj.validateDaqChoice,...
                'TooltipString', '', ...
                'Bindings',{obj 'galvoDaq' 'string'});

            % GalvoXGalvoPanel
            xygph = 210;
            obj.hGalvoXGalvoPanel = uipanel( ...
                'parent', obj.hGalvoPanel, ...
                'Tag', 'GalvoXGalvoPanel', ...
                'Title', 'X Galvo (Optional)', ...    
                'Units', 'pixels', ...
                'Position', [46 gph-289 332 xygph]);

            % XGalvoAnalogOutputChannelIDText
            obj.hXGalvoAnalogOutputChannelIDText = uicontrol(...
                'parent', obj.hGalvoXGalvoPanel, ...
                'Tag', 'XGalvoAnalogOutputChannelIDText', ...
                'Style', 'text', ...
                'String', 'Position Control AO Channel ID', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [36 xygph-53 198 14]);
        
            % XGalvoAnalogOutputChannelIDPopUp 
            obj.hXGalvoAnalogOutputChannelIDPopUp = most.gui.uicontrol(...
                'parent', obj.hGalvoXGalvoPanel, ...
                'Tag', 'XGalvoAnalogOutputChannelIDPopUp', ...
                'Style', 'popupmenu', ...
                'String', ' ', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Bindings',{obj 'xGalvoChanSel' 'value'},...
                'Position', [246 xygph-55 50 20]);

            % XGalvoMaxAngularRangeText
            obj.hXGalvoMaxAngularRangeText = uicontrol(...
                'parent', obj.hGalvoXGalvoPanel, ...
                'Tag', 'XGalvoMaxAngularRangeText', ...
                'Style', 'text', ...
                'String', 'Max Angular Range (optical deg pk-pk)', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [36 xygph-94 189 14]);
        
            % XGalvoMaxAngularRangeEdit 
            obj.hXGalvoMaxAngularRangeEdit = uicontrol(...
                'parent', obj.hGalvoXGalvoPanel, ...
                'Tag', 'XGalvoMaxAngularRangeEdit', ...
                'Style', 'edit', ...
                'String', '15', ...
                'HorizontalAlignment', 'center', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [246 xygph-98 50 22]);
        
            % XGalvoOpticalConversionFactorText
            obj.hXGalvoOpticalConversionFactorText = uicontrol(...
                'parent', obj.hGalvoXGalvoPanel, ...
                'Tag', 'XGalvoOpticalConversionFactorText', ...
                'Style', 'text', ...
                'String', 'Command Scaling Factor (V/optical deg)', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [36 xygph-137 199 14]);
        
            % XGalvoOpticalConversionFactorEdit 
            obj.hXGalvoOpticalConversionFactorEdit = uicontrol(...
                'parent', obj.hGalvoXGalvoPanel, ...
                'Tag', 'XGalvoOpticalConversionFactorEdit', ...
                'Style', 'edit', ...
                'String', '1', ...
                'HorizontalAlignment', 'center', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [246 xygph-141 50 22]);
        
            % XGalvoParkAngleText
            obj.hXGalvoParkAngleText = uicontrol(...
                'parent', obj.hGalvoXGalvoPanel, ...
                'Tag', 'XGalvoParkAngleText', ...
                'Style', 'text', ...
                'String', 'Park Angle (optical deg)', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [36 xygph-182 140 14]);
        
            % XGalvoParkAngleEdit 
            obj.hXGalvoParkAngleEdit = uicontrol(...
                'parent', obj.hGalvoXGalvoPanel, ...
                'Tag', 'XGalvoParkAngleEdit', ...
                'Style', 'edit', ...
                'String', '-8', ...
                'HorizontalAlignment', 'center', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [246 xygph-184 50 22]);
        
            % GalvoYGalvoPanel
            obj.hGalvoYGalvoPanel = uipanel( ...
                'parent', obj.hGalvoPanel, ...
                'Tag', 'GalvoYGalvoPanel', ...
                'Title', 'Y Galvo', ...    
                'Units', 'pixels', ...
                'Position', [424 gph-289 332 xygph]);
        
            % YGalvoAnalogOutputChannelIDText
            obj.hYGalvoAnalogOutputChannelIDText = uicontrol(...
                'parent', obj.hGalvoYGalvoPanel, ...
                'Tag', 'YGalvoAnalogOutputChannelIDText', ...
                'Style', 'text', ...
                'String', 'Position Control AO Channel ID', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [36 xygph-53 198 14]);
        
            % YGalvoAnalogOutputChannelIDPopUp 
            obj.hYGalvoAnalogOutputChannelIDPopUp = uicontrol(...
                'parent', obj.hGalvoYGalvoPanel, ...
                'Tag', 'YGalvoAnalogOutputChannelIDPopUp', ...
                'Style', 'popupmenu', ...
                'String', ' ', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [246 xygph-55 50 20]);

            % YGalvoMaxAngularRangeText
            obj.hYGalvoMaxAngularRangeText = uicontrol(...
                'parent', obj.hGalvoYGalvoPanel, ...
                'Tag', 'YGalvoMaxAngularRangeText', ...
                'Style', 'text', ...
                'String', 'Max Angular Range (optical deg pk-pk)', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [36 xygph-94 189 14]);
        
            % YGalvoMaxAngularRangeEdit 
            obj.hYGalvoMaxAngularRangeEdit = uicontrol(...
                'parent', obj.hGalvoYGalvoPanel, ...
                'Tag', 'YGalvoMaxAngularRangeEdit', ...
                'Style', 'edit', ...
                'String', '15', ...
                'HorizontalAlignment', 'center', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [246 xygph-98 50 22]);
        
            % YGalvoOpticalConversionFactorText
            obj.hYGalvoOpticalConversionFactorText = uicontrol(...
                'parent', obj.hGalvoYGalvoPanel, ...
                'Tag', 'YGalvoOpticalConversionFactorText', ...
                'Style', 'text', ...
                'String', 'Command Scaling Factor (V/optical deg)', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [36 xygph-137 198 14]);
        
            % YGalvoOpticalConversionFactorEdit 
            obj.hYGalvoOpticalConversionFactorEdit = uicontrol(...
                'parent', obj.hGalvoYGalvoPanel, ...
                'Tag', 'YGalvoOpticalConversionFactorEdit', ...
                'Style', 'edit', ...
                'String', '1', ...
                'HorizontalAlignment', 'center', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [246 xygph-141 50 22]);
        
            % YGalvoParkAngleText
            obj.hYGalvoParkAngleText = uicontrol(...
                'parent', obj.hGalvoYGalvoPanel, ...
                'Tag', 'YGalvoParkAngleText', ...
                'Style', 'text', ...
                'String', 'Park Angle (optical deg)', ...
                'HorizontalAlignment', 'left', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [36 xygph-182 140 14]);
        
            % YGalvoParkAngleEdit 
            obj.hYGalvoParkAngleEdit = uicontrol(...
                'parent', obj.hGalvoYGalvoPanel, ...
                'Tag', 'YGalvoParkAngleEdit', ...
                'Style', 'edit', ...
                'String', '-8', ...
                'HorizontalAlignment', 'center', ...
                'TooltipString', '', ...
                'Units', 'pixels', ...
                'Position', [246 xygph-184 50 22]);
            
            obj.hConfigEditor.addSimRio();
            obj.reload(scannerName);
        end
        
        function delete(~)
        end
        
        function applySmartDefaultSettings(obj,scannerName)
            if nargin > 1 && ~isempty(scannerName)
                obj.heading = ['ResScan (' scannerName ')'];
            end
            
            s = [];
            
            % change settings to appropriate default values
            if ~isempty(obj.hConfigEditor.availableRios)
                s.rioDeviceID = obj.hConfigEditor.availableRios{1};
                pxiN = obj.hConfigEditor.rioInfo.(s.rioDeviceID).pxiNumber;
                % find an x series daq in the same chassis
                dq = find(([obj.hConfigEditor.daqInfo.pxiNum] == pxiN) & [obj.hConfigEditor.daqInfo.isXSer],1);
            else
                % find an x series daq in a chassis
                dq = find(~isnan([obj.hConfigEditor.daqInfo.pxiNum]) & [obj.hConfigEditor.daqInfo.isXSer],1);
            end
            
            if ~isempty(dq)
                s.digitalIODeviceName = obj.hConfigEditor.availableDaqs{dq};
                s.galvoDeviceName = s.digitalIODeviceName;
                s.resonantZoomDeviceName = s.digitalIODeviceName;
            end
            
            if ~isempty(s)
                obj.applyVarStruct(s);
                obj.reload();
            end
        end
        
        function refreshPageDependentOptions(obj)
            shutterIDs = find([obj.hShutterTable.Data{:,1}]);
            
            shutters = obj.hConfigEditor.shutterNames;
            shutterDat = [repmat({false},numel(shutters),1) shutters];
            obj.hShutterTable.Data = shutterDat;
            
            if ~isempty(shutterIDs)
                shutterIDs(shutterIDs > numel(shutters)) = [];
                obj.hShutterTable.Data(:,1) = {false};
                obj.hShutterTable.Data(shutterIDs,1) = {true};
            end
            
            str = [{'None'} obj.hConfigEditor.beamDaqNames];
            v = min(numel(str),obj.hBeamPopUp.Value);
            obj.hBeamPopUp.String = str;
            obj.hBeamPopUp.Value = v;
        end
        
        function reload(obj,scannerName)
            if nargin > 1
                obj.scannerName = scannerName;
                obj.listLabel = ['Scanner Settings (' scannerName ')'];
                obj.heading = ['ResScan (' scannerName ')'];
                obj.descriptionText = ['Configure DAQ and scan mirror settings for the ''' scannerName ''' resonant scanning system. Previously configured beam DAQs and shutters can be assigned to this scanner. A resonant '...
                    'scan system has at minimum a resonant X mirror and a galvo Y mirror. Optionally a galvo X mirror can be included for enhanced multi-RIO imaging.'];
            end
            
            obj.refreshPageDependentOptions();
            
            obj.hBeamPopUp.String = {'None' obj.hConfigEditor.beamDaqNames{:}};
            
            obj.hResZoomDevicePopUp.choices = obj.hConfigEditor.availableDaqs;
            
            % reload the settings
            mdfData = obj.getCurrentMdfDataStruct();
            
            if ~isempty(mdfData.beamDaqID) && mdfData.beamDaqID <= obj.hConfigEditor.numBeamDaqs
                obj.hBeamPopUp.Value = mdfData.beamDaqID+1;
            else
                obj.hBeamPopUp.Value = 1;
            end
            
            if isempty(mdfData.rioDeviceID)
                obj.acqDev = 'RIO0';
            else
                obj.acqDev = mdfData.rioDeviceID;
            end
            
            mdfData.channelsInvert(end+1:obj.numChans) = mdfData.channelsInvert(1);
            mdfData.channelsInvert(obj.numChans+1:end) = [];
            obj.hChannelTable.Data(:,2) = num2cell(mdfData.channelsInvert(:));
            
            obj.digIoDev = mdfData.digitalIODeviceName;
            
            obj.useExtClk = mdfData.externalSampleClock;
            obj.hExternalSampleClockRateEdit.String = mdfData.externalSampleClockRate;
            
            if isfield(mdfData,'enableRefClkOutput')
                obj.exprtClk = mdfData.enableRefClkOutput;
            else
                obj.exprtClk = false;
            end
            
            mdfData.shutterIDs(mdfData.shutterIDs > obj.hConfigEditor.numShutters) = [];
            obj.hShutterTable.Data(:,1) = {false};
            obj.hShutterTable.Data(mdfData.shutterIDs,1) = {true};
            
            if isempty(mdfData.resonantZoomDeviceName)
                mdfData.resonantZoomDeviceName = mdfData.galvoDeviceName;
            end
            obj.zoomCtlDaq = mdfData.resonantZoomDeviceName;
            
            nchcs = numel(obj.hResZoomChannelIDPopUp.String);
            obj.hResZoomChannelIDPopUp.Value = min(nchcs,mdfData.resonantZoomAOChanID+1);
            
            obj.hResMaxAngularRangeEdit.String = mdfData.resonantAngularRange;
            
            v = mdfData.rScanVoltsPerOpticalDegree*mdfData.resonantAngularRange;
            obj.hResMaxVoltageCmdEdit.String = round(v*1000)/1000;
            
            obj.hResSettlingTimeEdit.String = mdfData.resonantScannerSettleTime;
            
            obj.hNominalFrequencyEdit.String = mdfData.nominalResScanFreq;
            
            obj.galvoDaq = mdfData.galvoDeviceName;
            
            if isempty(mdfData.galvoAOChanIDX)
                obj.xGalvoChanSel = 1;
            else
                nchcs = numel(obj.hXGalvoAnalogOutputChannelIDPopUp.String);
                obj.xGalvoChanSel = min(nchcs,mdfData.galvoAOChanIDX+2);
            end
            obj.hXGalvoMaxAngularRangeEdit.String = mdfData.xGalvoAngularRange;
            obj.hXGalvoOpticalConversionFactorEdit.String = mdfData.galvoVoltsPerOpticalDegreeX;
            obj.hXGalvoParkAngleEdit.String = mdfData.galvoParkDegreesX;
            
            nchcs = numel(obj.hYGalvoAnalogOutputChannelIDPopUp.String);
            obj.hYGalvoAnalogOutputChannelIDPopUp.Value = min(nchcs,mdfData.galvoAOChanIDY+1);
            obj.hYGalvoMaxAngularRangeEdit.String = mdfData.yGalvoAngularRange;
            obj.hYGalvoOpticalConversionFactorEdit.String = mdfData.galvoVoltsPerOpticalDegreeY;
            obj.hYGalvoParkAngleEdit.String = mdfData.galvoParkDegreesY;
        end
        
        function s = getNewVarStruct(obj)
            s.beamDaqID = obj.hBeamPopUp.Value - 1;
            if s.beamDaqID < 1
                s.beamDaqID = [];
            end
            
            s.shutterIDs = find([obj.hShutterTable.Data{:,1}]);
            if isempty(s.shutterIDs)
                s.shutterIDs = [];
            end
            
            s.channelsInvert = [obj.hChannelTable.Data{:,2}];
            
            s.digitalIODeviceName = obj.digIoDev;
            
            s.externalSampleClock = logical(obj.useExtClk);
            s.externalSampleClockRate = str2double(obj.hExternalSampleClockRateEdit.String);
            if isnan(s.externalSampleClockRate)
                s.externalSampleClockRate = [];
            end
            
            s.enableRefClkOutput = logical(obj.exprtClk);
            
            rio = strsplit(obj.acqDev,' (');
            s.rioDeviceID = rio{1};
            if (numel(rio) > 1) && isempty(strfind(rio{2},'not found'))
                fpgaDig = strsplit(strrep(rio{2},')',''),',');
                s.fpgaModuleType = fpgaDig{1};
                if numel(fpgaDig) > 1
                    s.digitizerModuleType = strtrim(fpgaDig{2});
                else
                    if strncmp(s.fpgaModuleType,'NI5171',6)
                        s.fpgaModuleType = 'NI5171';
                    end
                    s.digitizerModuleType = '';
                end
            else
                s.fpgaModuleType = 'NI7961';
                s.digitizerModuleType = 'NI5732';
            end
            
            s.nominalResScanFreq = str2double(obj.hNominalFrequencyEdit.String);
            
            s.resonantZoomDeviceName = obj.zoomCtlDaq;
            s.resonantZoomAOChanID = obj.hResZoomChannelIDPopUp.Value-1;
            s.resonantAngularRange = str2num(obj.hResMaxAngularRangeEdit.String);
            v = str2num(obj.hResMaxVoltageCmdEdit.String) / s.resonantAngularRange;
            s.rScanVoltsPerOpticalDegree = round(v*10000)/10000;
            s.resonantScannerSettleTime = str2double(obj.hResSettlingTimeEdit.String);
            
            s.galvoDeviceName = obj.galvoDaq;
            
            if obj.xGalvoChanSel > 1
                s.galvoAOChanIDX = obj.xGalvoChanSel - 2;
            else
                s.galvoAOChanIDX = [];
            end
            s.galvoParkDegreesX = str2double(obj.hXGalvoParkAngleEdit.String);
            s.galvoVoltsPerOpticalDegreeX = str2num(obj.hXGalvoOpticalConversionFactorEdit.String);
            s.xGalvoAngularRange = str2num(obj.hXGalvoMaxAngularRangeEdit.String);
            
            s.galvoAOChanIDY = obj.hYGalvoAnalogOutputChannelIDPopUp.Value-1;
            s.galvoParkDegreesY = str2double(obj.hYGalvoParkAngleEdit.String);
            s.galvoVoltsPerOpticalDegreeY = str2num(obj.hYGalvoOpticalConversionFactorEdit.String);
            s.yGalvoAngularRange = str2num(obj.hYGalvoMaxAngularRangeEdit.String);
        end
        
        function [lvl,v,errMsg] = validateRioChoice(obj,v,oldV)
            allowChange = false;
            lvl = 2;
            errMsg = 'Error: must be a valid RIO ID';
            if strncmp(v,'RIO',3)
                vs = strtrim(strsplit(v,'('));
                allowChange = all(isstrprop(vs{1}(4:end), 'digit'));
                if ismember(vs{1},obj.hConfigEditor.availableRios)
                    lvl = 0;
                    errMsg = '';
                end
            end
            if ~allowChange
                v = oldV;
            end
        end
        
        function [lvl,v,errMsg] = validateDaqChoice(obj,v,oldV)
            errMsg = '';
%             allowChange = isvarname(v);
            lvl = 2 * ~ismember(v,obj.hDigitalIODevicePopUp.choices);
            if lvl > 0
                errMsg = 'Error: must be an X series DAQ in the same PXI chassis as the FPGA/digitizer';
            end
%             if ~allowChange
%                 v = oldV;
%             end
        end
        
        function [lvl,v,errMsg] = validateZoomDaqChoice(obj,v,oldV)
            errMsg = '';
%             allowChange = isvarname(v);
            lvl = 2 * ~ismember(v,obj.hResZoomDevicePopUp.choices);
            if lvl > 0
                errMsg = 'Error: must be a valid DAQ name';
            end
%             if ~allowChange
%                 v = oldV;
%             end
        end
    end
    
    %% prop access
    methods
        function set.acqDev(obj, v)
            rio = strsplit(v,' ');
            rio = rio{1};
            if isfield(obj.hConfigEditor.rioInfo, rio)
                obj.pxiNum = obj.hConfigEditor.rioInfo.(rio).pxiNumber;
                am = obj.hConfigEditor.rioInfo.(rio).adapterModule;
                if ~ismember(am,obj.ADAPTER_MODULE_CHANNEL_COUNT.keys)
                    am = '';
                end
            else
                obj.pxiNum = 1;
                am = '';
            end
            
            % make sure it is a selection from the list
            chcs = obj.hFlexRIODeviceIDPopUp.choices;
            idx = find(strncmp(rio, chcs, length(rio)),1);
            if isempty(idx)
                obj.acqDev = v;
            else
                obj.acqDev = chcs{idx};
            end
            
            % set list of valid daqs for the other drop downs
            daqChoices = obj.hConfigEditor.availableDaqs(([obj.hConfigEditor.daqInfo.pxiNum] == obj.pxiNum) & [obj.hConfigEditor.daqInfo.isXSer]);
            if isempty(daqChoices)
                daqChoices = {' '};
            end
            obj.hDigitalIODevicePopUp.choices = daqChoices;
            obj.hGalvoDevicePopUp.choices = daqChoices;
            
            % update channel table
            obj.numChans = obj.ADAPTER_MODULE_CHANNEL_COUNT(am);
            if obj.numChans
                dat = obj.hChannelTable.Data;
                dat(end+1:obj.numChans,2) = {false};
                dat(obj.numChans+1:end,:) = [];
                dat(:,1) = arrayfun(@(x)sprintf('AI%d',x),0:obj.numChans-1,'uniformoutput',false);
                obj.hChannelTable.RowName = arrayfun(@(x)sprintf('Channel %d',x),1:obj.numChans,'uniformoutput',false);
            else
                dat = {};
                obj.hChannelTable.RowName = dat;
            end
            obj.hChannelTable.Data = dat;
        end
        
        function set.useExtClk(obj, v)
            obj.hExternalSampleClockRateEdit.Enable = obj.tfMap(v);
            obj.useExtClk = v;
        end
        
        function set.zoomCtlDaq(obj, v)
            obj.zoomCtlDaq = v;
            
            [tf, idx] = ismember(v,obj.hConfigEditor.availableDaqs);
            if tf
                obj.hResZoomChannelIDPopUp.String = obj.hConfigEditor.daqInfo(idx).allAOs;
            else
                obj.hResZoomChannelIDPopUp.String = {' '};
            end
        end
        
        function set.galvoDaq(obj, v)
            obj.galvoDaq = v;
            
            [tf, idx] = ismember(v,obj.hConfigEditor.availableDaqs);
            if tf
                obj.hXGalvoAnalogOutputChannelIDPopUp.String = [{'None'} obj.hConfigEditor.daqInfo(idx).allAOs];
                obj.hYGalvoAnalogOutputChannelIDPopUp.String = obj.hConfigEditor.daqInfo(idx).allAOs;
            else
                obj.hXGalvoAnalogOutputChannelIDPopUp.String = {'None' 'AO0' 'AO1' 'AO2' 'AO3'};
                obj.hYGalvoAnalogOutputChannelIDPopUp.String = {'AO0' 'AO1' 'AO2' 'AO3'};
            end
        end
        
        function set.xGalvoChanSel(obj,v)
            obj.xGalvoChanSel = v;
            
            obj.hXGalvoMaxAngularRangeEdit.Enable = obj.tfMap(v > 1);
            obj.hXGalvoOpticalConversionFactorEdit.Enable = obj.tfMap(v > 1);
            obj.hXGalvoParkAngleEdit.Enable = obj.tfMap(v > 1);
        end
    end
end


%--------------------------------------------------------------------------%
% ResScanPage.m                                                            %
% Copyright © 2016 Vidrio Technologies, LLC                                %
%                                                                          %
% ScanImage 2016 is premium software to be used under the purchased terms  %
% Code may be modified, but not redistributed without the permission       %
% of Vidrio Technologies, LLC                                              %
%--------------------------------------------------------------------------%
