%% Example script that will run the full pipeline.
% This code block adds all modules inside the "core" directory to the
% matlab path.
% This isn't needed if the path to this package is added to the MATLAB path
% manually by right clicking caiman_matlab folder and "add packages and
% subpackages to path" or via the startup.m file. Both methods described in
% more detail in the README.

% general graphics, this will apply to any figure you open
% % (groot is the default figure object).
% set(groot, ...
% 'DefaultFigureColor', 'w', ...
% 'DefaultAxesLineWidth', 0.5, ...
% 'DefaultAxesXColor', 'k', ...
% 'DefaultAxesYColor', 'k', ...
% 'DefaultAxesFontUnits', 'points', ...
% 'DefaultAxesFontSize', 8, ...
% 'DefaultAxesFontName', 'Helvetica', ...
% 'DefaultLineLineWidth', 1, ...
% 'DefaultTextFontUnits', 'Points', ...
% 'DefaultTextFontSize', 8, ...
% 'DefaultTextFontName', 'Helvetica', ...
% 'DefaultAxesBox', 'off', ...
% 'DefaultAxesTickLength', [0.02 0.025]);
% 
% % set the tickdirs to go out - need this specific order
% set(groot, 'DefaultAxesTickDir', 'out');
% set(groot, 'DefaultAxesTickDirMode', 'manual');

%% UPDATE: RUN THIS WITH THE PLAY BUTTON, NOT "RUN SECTION"
% To get eveything added to your path

clc, clear;
[fpath, fname, ~] = fileparts(fullfile(mfilename('fullpath'))); % path to this script
addpath(genpath(fullfile(fpath, 'core')));
addpath(genpath(fullfile(fpath, 'core', 'utils')));

%% Here you can validate that all dependencies are on the path and accessible from within this pipeline.
% This does not check for package access on your path.

result = validate_toolboxes();
if ischar(result)
    error(result);
else
    disp('Proceeding with execution...');
end

data_path = fullfile('C:\Users\RBO\caiman_data\animal_01\session_01');

%%

%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%% Extraction %%%%%%%%
convertScanImageTiffToVolume( ...
    data_path, ...
    'ds','/Y', ... % default
    'debug_flag', 1, ...
    'do_figures', 1, ...
    'overwrite', 1, ...
    'fix_scan_phase', 1, ...
    'trim_roi', [6 6 17 0], ... % default, num pixels to trim for each roi
    'trim_image', [0 0 0 0] ... % default, num pixels to trim for each roi
);

%% 
motionCorrectPlane( ...
    fullfile(data_path, 'extracted'), ... % we used this to save extracted data
    'save_path', fullfile(data_path, 'registered'), ...
    'ds', '/Y', ... % where we saved the last step in h5
    'debug_flag', 1, ...
    'overwrite', 1, ...
    'num_cores', 15, ...
    'start_plane', 1, ...
    'end_plane', 2  ...
);

segmentPlane( ...
    fullfile(data_path, 'registered'), ... % we used this to save extracted data
    'save_path', fullfile(data_path, 'segmented'), ... % save registered data here
    'ds', '/Y', ... % where we saved the last step in h5
    'debug_flag', 0, ...
    'overwrite', 0, ...
    'num_cores', 15, ...
    'start_plane', 1, ...
    'end_plane', 2  ...
    );